# Generated by Django 3.2 on 2021-04-11 09:32

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bench',
            fields=[
                ('bench_num', models.IntegerField(primary_key=True, serialize=False)),
                ('isOccupied', models.BooleanField(default=True, verbose_name='Table available')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('Ingredient_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Ingredient_name', models.CharField(max_length=20)),
                ('Ingredient_available', models.BooleanField(default=True, verbose_name='Ingredient available')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=20)),
                ('meal_price', models.IntegerField(max_length=10)),
                ('Rating', models.IntegerField(max_length=1)),
                ('Est_Time', models.DateTimeField(verbose_name='Entry time')),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('waiter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('waiter_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Waiter_phone',
            fields=[
                ('waiter_phoneNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region=None, serialize=False)),
                ('waiter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.waiter')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('Customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=20)),
                ('Customer_address', models.CharField(max_length=100)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('billing_amt', models.IntegerField()),
                ('people_accompanying', models.IntegerField(max_length=10)),
                ('Timestamp', models.DateTimeField(verbose_name='Entry time')),
                ('bench_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.bench')),
            ],
        ),
        migrations.CreateModel(
            name='Bench_meal',
            fields=[
                ('ComboID', models.IntegerField(primary_key=True, serialize=False)),
                ('isOccupied', models.BooleanField(default=True, verbose_name='Table available')),
                ('Ingredient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.ingredient')),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.meal')),
            ],
        ),
        migrations.AddField(
            model_name='bench',
            name='waiter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.waiter'),
        ),
    ]
